"""Grand Intellect constitutional runtime."""

from .agents import AgentCouncil, AgentRegistry, OfficeAgent
from .constitution import Constitution, GateReport
from .engine import GrandIntellect
from .fabric import InMemoryFabric
from .maintenance_contract import (
    ACCELERATION_FACTOR,
    ADOPTION_ID,
    EXPECTED_DURATIONS,
    INTELLECT_ISSUE,
    PHASE_A,
    PHASE_B,
    PROGRAMME_CONTROL_ID as MAINTENANCE_PROGRAMME_CONTROL_ID,
    PROGRAMME_DECISION_ID as MAINTENANCE_PROGRAMME_DECISION_ID,
    PROGRAMME_MIRROR_POLICY_ID as MAINTENANCE_PROGRAMME_MIRROR_POLICY_ID,
    PROGRAMME_PULL_REQUEST as MAINTENANCE_PROGRAMME_PULL_REQUEST,
    PROGRAMME_REPOSITORY as MAINTENANCE_PROGRAMME_REPOSITORY,
    REQUIRED_PROTECTED_ARTIFACTS as MAINTENANCE_REQUIRED_PROTECTED_ARTIFACTS,
    maintenance_adoption_errors,
)
from .mathsolve import (
    ADJUDICATED_HANDOFF_STATES,
    ALL_HANDOFF_STATES,
    INTAKE_HANDOFF_STATES,
    MATHCERT_PROVIDER_COMMIT,
    MATHCERT_ROUTE_REGISTRY_DIGEST,
    MATHCERT_ROUTE_REGISTRY_PATH,
    MATHSOLVE_CURRENT_CERT_ROUTES_DIGEST,
    MATHSOLVE_CURRENT_CERT_ROUTES_PATH,
    MATHSOLVE_PROVIDER_COMMIT,
    PROGRAMME_CANDIDATE_ADMISSION_DIGEST,
    PROGRAMME_CANDIDATE_ADMISSION_PATH,
    PROGRAMME_POLICY_COMMIT,
    PROGRAMME_POLICY_DIGEST,
    PROGRAMME_POLICY_PATH,
    PROGRAMME_RUNTIME_CONTRACT_DIGEST,
    PROGRAMME_RUNTIME_CONTRACT_PATH,
    PROGRAMME_UMBRELLA_STATE_DIGEST,
    PROGRAMME_UMBRELLA_STATE_PATH,
    PROMOTING_HANDOFF_STATES,
    GitHubArtifactRef,
    MathematicalConstitution,
    MathematicalGrandIntellect,
    MathSolveProvider,
)
from .metrics import WorkPackageMetrics, calculate_metrics
from .model import Office, Phase, ReviewStatus
from .trove_curata_contract import (
    EXPECTED_RECORD_CONTRACTS as TROVE_CURATA_RECORD_CONTRACTS,
    EXPECTED_REVIEW_TIERS as TROVE_CURATA_REVIEW_TIERS,
    TroveCurataContractError,
    load_and_validate_trove_curata_contract,
    validate_trove_curata_contract,
)
from .workspace import WorkPackageWorkspace

__all__ = [
    "ACCELERATION_FACTOR",
    "ADJUDICATED_HANDOFF_STATES",
    "ADOPTION_ID",
    "ALL_HANDOFF_STATES",
    "AgentCouncil",
    "AgentRegistry",
    "Constitution",
    "EXPECTED_DURATIONS",
    "GateReport",
    "GitHubArtifactRef",
    "GrandIntellect",
    "INTAKE_HANDOFF_STATES",
    "INTELLECT_ISSUE",
    "InMemoryFabric",
    "MAINTENANCE_PROGRAMME_CONTROL_ID",
    "MAINTENANCE_PROGRAMME_DECISION_ID",
    "MAINTENANCE_PROGRAMME_MIRROR_POLICY_ID",
    "MAINTENANCE_PROGRAMME_PULL_REQUEST",
    "MAINTENANCE_PROGRAMME_REPOSITORY",
    "MAINTENANCE_REQUIRED_PROTECTED_ARTIFACTS",
    "MATHCERT_PROVIDER_COMMIT",
    "MATHCERT_ROUTE_REGISTRY_DIGEST",
    "MATHCERT_ROUTE_REGISTRY_PATH",
    "MATHSOLVE_CURRENT_CERT_ROUTES_DIGEST",
    "MATHSOLVE_CURRENT_CERT_ROUTES_PATH",
    "MATHSOLVE_PROVIDER_COMMIT",
    "MathematicalConstitution",
    "MathematicalGrandIntellect",
    "MathSolveProvider",
    "Office",
    "OfficeAgent",
    "PHASE_A",
    "PHASE_B",
    "PROGRAMME_CANDIDATE_ADMISSION_DIGEST",
    "PROGRAMME_CANDIDATE_ADMISSION_PATH",
    "PROGRAMME_POLICY_COMMIT",
    "PROGRAMME_POLICY_DIGEST",
    "PROGRAMME_POLICY_PATH",
    "PROGRAMME_RUNTIME_CONTRACT_DIGEST",
    "PROGRAMME_RUNTIME_CONTRACT_PATH",
    "PROGRAMME_UMBRELLA_STATE_DIGEST",
    "PROGRAMME_UMBRELLA_STATE_PATH",
    "PROMOTING_HANDOFF_STATES",
    "Phase",
    "ReviewStatus",
    "TROVE_CURATA_RECORD_CONTRACTS",
    "TROVE_CURATA_REVIEW_TIERS",
    "TroveCurataContractError",
    "WorkPackageMetrics",
    "WorkPackageWorkspace",
    "calculate_metrics",
    "load_and_validate_trove_curata_contract",
    "maintenance_adoption_errors",
    "validate_trove_curata_contract",
]

__version__ = "0.2.2"
